elections:
# Elections listed in reverse chronological order.
-
  dir_name: "2022-11-08"  # use quotes to prevent conversion to a date.
  name: November 8, 2022 Consolidated General Election
  url: https://sfelections.sfgov.org/november-8-2022-election-results-summary
  contests:
  -
    file: da_short
    url: https://www.sfelections.org/results/20221108/data/20221201/da/da_short.pdf
  -
    file: defender_short
    url: https://www.sfelections.org/results/20221108/data/20221201/defender/defender_short.pdf
  -
    file: d4_short
    url: https://www.sfelections.org/results/20221108/data/20221201/d4/d4_short.pdf
  -
    file: d6_short
    url: https://www.sfelections.org/results/20221108/data/20221201/d6/d6_short.pdf
  -
    file: d8_short
    url: https://www.sfelections.org/results/20221108/data/20221201/d8/d8_short.pdf
  -
    file: d10_short
    url: https://www.sfelections.org/results/20221108/data/20221201/d10/d10_short.pdf
-
  dir_name: "2022-02-15"  # use quotes to prevent conversion to a date.
  name: February 15, 2022 Consolidated Special Municipal Election
  url: https://sfelections.sfgov.org/february-15-2022-election-results-summary
  contests:
  -
    file: 20220223_ar
    url: https://www.sfelections.org/results/20220215/data/20220223/ar/20220223_ar.pdf
-
  dir_name: "2020-11-03"  # use quotes to prevent conversion to a date.
  name: November 3, 2020 Consolidated General Election
  url: https://sfelections.sfgov.org/november-3-2020-election-results-summary
  contests:
  -
    file: 20201201_d1_short
    url: https://www.sfelections.org/results/20201103/data/20201201/d1/20201201_d1_short.pdf
  -
    file: 20201201_d3_short
    url: https://www.sfelections.org/results/20201103/data/20201201/d3/20201201_d3_short.pdf
  -
    file: 20201201_d5_short
    url: https://www.sfelections.org/results/20201103/data/20201201/d5/20201201_d5_short.pdf
  -
    file: 20201201_d7_short
    url: https://www.sfelections.org/results/20201103/data/20201201/d7/20201201_d7_short.pdf
  -
    file: 20201201_d9_short
    url: https://www.sfelections.org/results/20201103/data/20201201/d9/20201201_d9_short.pdf
  -
    file: 20201201_d11_short
    url: https://www.sfelections.org/results/20201103/data/20201201/d11/20201201_d11_short.pdf

# TODO: uncomment this.
# -
#   dir_name: 2019-11-05
#   name: November 5, 2019 Consolidated Municipal Election
#   url: https://sfelections.sfgov.org/november-5-2019-election-results-summary
