elections:
# Elections listed in reverse chronological order.
-
  dir_name: 2022-11-08
  name: November 8, 2022 Consolidated General Election
  url: https://sfelections.sfgov.org/november-8-2022-election-results-summary
-
  dir_name: 2022-02-15
  name: February 15, 2022 Consolidated Special Municipal Election
  url: https://sfelections.sfgov.org/february-15-2022-election-results-summary
-
  dir_name: 2020-11-03
  name: November 3, 2020 Consolidated General Election
  url: https://sfelections.sfgov.org/november-3-2020-election-results-summary
# TODO: uncomment this.
# -
#   dir_name: 2019-11-05
#   name: November 5, 2019 Consolidated Municipal Election
#   url: https://sfelections.sfgov.org/november-5-2019-election-results-summary
