version: 2.1
orbs:
  python: circleci/python@2.1.1
jobs:
  run-tests-and-build-demo:
    executor:
      name: python/default
      # TODO: test on all versions 3.9+?
      tag: "3.9"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements/requirements.txt
          # Also install the project in editable mode.
          args: "-e ."
      - run:
          name: "Run tests"
          command: python -m unittest discover rcvresults
      - run:
          name: "Build demo"
          command: ./build-demo.sh tmp/build
      - persist_to_workspace:
          root: tmp
          paths:
            - build
  deploy-demo:
    # TODO: choose a better executor.
    executor:
      name: python/default
      tag: "3.9"
    steps:
      - checkout
      - run: git checkout gh-pages
      - attach_workspace:
          at: tmp
      # We need to use the -T option to prevent cp from copying the
      # files into a "build" subfolder of the current directory.
      - run: cp -RT tmp/build/ .
      # TODO: finish this.
      - run: git add -u
      - run: git config --global user.email "chris.jerdonek@gmail.com"
      - run: git config --global user.name "Chris Jerdonek"
      - run: git commit -m "Regenerate files from CI."
      - run: git push
workflows:
  run-tests-and-deploy-demo:
    jobs:
      - run-tests-and-build-demo
      - deploy-demo:
          requires:
            - run-tests-and-build-demo
          filters:
            branches:
              only: main
