version: 2.1
orbs:
  python: circleci/python@2.1.1
# TODO: add a job or steps to deploy the demo page.
jobs:
  test:
    executor:
      name: python/default
      # TODO: test on all versions 3.9+?
      tag: "3.9"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements/requirements.txt
          # Also install the project in editable mode.
          args: "-e ."
      - run:
          name: "Run tests"
          command: python -m unittest discover rcvresults
workflows:
  run-tests:
    jobs:
      - test
