version: 2.1
orbs:
  python: circleci/python@2.1.1
jobs:
  run-tests-and-build-demo:
    executor:
      name: python/default
      # TODO: test on all versions 3.9+?
      tag: "3.9"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements/requirements.txt
          # Also install the project in editable mode.
          args: "-e ."
      - run:
          name: "Run tests"
          command: python -m unittest discover rcvresults
      - run:
          name: "Build demo"
          command: ./build-demo.sh tmp/build
      - persist_to_workspace:
          root: tmp
          paths:
            - build
  deploy-demo:
    docker:
      - image: cimg/base:2023.08
    steps:
      - checkout
      - run:
          name: "Checkout gh-pages branch"
          command: git checkout gh-pages
      - attach_workspace:
          at: tmp
      - run:
          name: "Commit the new demo build"
          command: |
            # Remove all the checked-in files.
            git rm -r .
            # We need to use the -T option to prevent cp from copying the
            # files into a "build" subfolder of the current directory.
            cp -RT tmp/build/ .
            rm -r tmp/build
            git add -A .
            echo "running: git status"
            git status
            git config --global user.email "chris.jerdonek@gmail.com"
            git config --global user.name "Chris Jerdonek"
            # TODO: include the commit sha in the commit message?
            git commit --allow-empty -m "[CI] Rebuild the demo."
      - run:
          name: "Push demo"
          command: git push
workflows:
  run-tests-and-deploy-demo:
    jobs:
      - run-tests-and-build-demo
      - deploy-demo:
          requires:
            - run-tests-and-build-demo
          filters:
            branches:
              only: main
