version: 2.1
orbs:
  python: circleci/python@2.1.1
jobs:
  run-tests:
    parameters:
      python-version:
        type: string
    executor:
      name: python/default
      tag: << parameters.python-version >>
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements/requirements.txt
          # Also install the project in editable mode.
          args: "-e ."
      - run:
          name: "Run tests"
          command: python -m unittest discover rcvresults
  build-demo:
    executor:
      name: python/default
      # TODO: run on a newer version of Python?
      tag: "3.9"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements/requirements.txt
          # Also install the project in editable mode.
          args: "-e ."
      - run:
          name: "Build demo"
          command: ./build-demo.sh tmp/build
      - persist_to_workspace:
          root: tmp
          paths:
            - build
  deploy-demo:
    docker:
      - image: cimg/base:2023.08
    steps:
      - checkout
      - run:
          name: "Checkout gh-pages branch"
          command: git checkout gh-pages
      - attach_workspace:
          at: tmp
      - run:
          name: "Stage the new demo files"
          command: |
            # Remove all the checked-in files.
            git rm -r .
            # Restore the no-op Circle CI config file.
            git restore --staged --worktree .circleci/config.yml
            # We need to use the -T option to prevent cp from copying the
            # files into a "build" subfolder of the current directory.
            cp -RT tmp/build/ .
            rm -r tmp/build
            git add -A .
            echo "running: git status"
            git status
      - run:
          name: "Commit the new demo"
          command: |
            git config --global user.email "chris.jerdonek@gmail.com"
            git config --global user.name "Chris Jerdonek"
            # Include the commit sha in the commit message for reference.
            git commit --allow-empty -m "[CI] Rebuild the demo: ${CIRCLE_SHA1}"
      - run:
          name: "Push demo"
          command: git push
workflows:
  run-tests-and-deploy-demo:
    # The "requires" keys below force sequential execution of jobs:
    # https://circleci.com/docs/workflows/#sequential-job-execution
    jobs:
      - run-tests:
          matrix:
            parameters:
              python-version: ["3.9"]
      # Only build and deploy the demo from "main".
      - build-demo:
          requires:
            - run-tests
          filters:
            branches:
              only: main
      - deploy-demo:
          requires:
            - build-demo
