election:
  name: February 15, 2022 Consolidated Special Municipal Election
  url: https://sfelections.sfgov.org/february-15-2022-election-results-summary
  contests:
  -
    file_stem: 20220223_ar
    pdf_url: https://www.sfelections.org/results/20220215/data/20220223/ar/20220223_ar.pdf
