# This is the file of extra template context variables to pass as the
# --template-vars option when running scripts/build_demo.py in CI
# (i.e. in build-demo.sh).
contexts:
  "index-all-rcv.html":
    # This is the URL to the directory containing the "js" and "styles"
    # directories for the main index pages. It can be an absolute url
    # or else a relative url relative to the location of the index page
    # in the url hierarchy. It must end in a slash ("/").
    parent_static_url_dir: static-files/

  'rcv-complete.html':
    # This is the URL for the CSS file to use in the html template for the
    # RCV round-by-round report.
    #   The RCV round-by-round pages for the demo are at the following
    # location relative to the repo in CI (as controlled by the BUILD_DIR
    # argument passed to build-demo.sh in .circleci/config.yml), so we
    # need to navigate up 3 levels to get to the **site** root (not
    # repo root):
    #  * tmp/build/rcv-snippets/2022-11-08/round-pages/
    #     da_short-rounds-en.html
    css_url: ../../../static-files-rcv/styles/rcv-rounds.css
